name: Build

on: [push, pull_request]

jobs:
  test:
    uses: ./.github/workflows/test.yml
    secrets: inherit

  package-linux:
    name: Linux package
    uses: ./.github/workflows/build-linux.yml
    with:
      artifact-name: dfhack-linux64-build
      append-date-and-hash: true
      cache-id: release
      stonesense: true
      docs: true
    secrets: inherit

  package-win64:
    name: Win64 package
    uses: ./.github/workflows/build-windows.yml
    with:
      artifact-name: dfhack-win64-build
      append-date-and-hash: true
      cache-id: release
      stonesense: true
      docs: true
    secrets: inherit

  docs:
    uses: ./.github/workflows/build-linux.yml
    with:
      platform-files: false
      common-files: false
      docs: true
    secrets: inherit

  lint:
    uses: ./.github/workflows/lint.yml
    secrets: inherit

  check-pr:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
    - name: Check that PR is based on develop branch
      env:
        BASE_BRANCH: ${{ github.base_ref }}
      run: |
        echo "PR base branch: $BASE_BRANCH"
        test "$BASE_BRANCH" = develop
